mqtt:
  endpoint: a23bq50uzv6v7o-ats.iot.ap-south-1.amazonaws.com
  cert:
   path: ./mqttcerts/TestLaptopNikhil.cert.pem
  key:
   path: ./mqttcerts/TestLaptopNikhil.private.key
  ca:
   path: ./mqttcerts/root-CA.crt
  subscribe:
   topic: sdk/modbus/request/dev
  publish:
   topic: sdk/modbus/response/dev
  client:
   id: 'remotestation_dev_client'

spring:
  main:
   banner-mode: log

logging:
   level:
     root: INFO
     com:
      dwellsmart: DEBUG
   file:
     path: logs
