spring:
  application:
    name: mqtt-client
  main:
    banner-mode: console
  profiles:
    active: '@spring.profiles.active@'

# Default Logging Level
logging:
  level:
    com:
     dwellsmart: INFO
    root: INFO
  file:
    path: logs
#logging.config: classpath:logback-spring.xml


